zellij and images

diff --git a/scripts/tag b/scripts/tag
--- a/scripts/tag
+++ b/scripts/tag
@@ -1,20 +1,22 @@
 #!/bin/sh
 
-# err() { echo "Usage:
-#     tag [OPTIONS] file
-# Options:
-#     -a: artist/author
-#     -t: song/chapter title
-#     -A: album/book title
-#     -n: track/chapter number
-#     -N: total number of tracks/chapters
-#     -d: year of publication
-#     -g: genre
-#     -c: comment
-# You will be prompted for title, artist, album and track if not given." && exit 1 ;
-# }
+err() { echo "Usage:
+    tag [OPTIONS] file
+Options:
+    -I: dont hide the image
+" && exit 1 ;
+}
 
-# while getopts "a:t:A:n:N:d:g:c:" o; do case "${o}" in
+    # -t: song/chapter title
+    # -A: album/book title
+    # -n: track/chapter number
+    # -N: total number of tracks/chapters
+    # -d: year of publication
+    # -g: genre
+    # -c: comment
+
+while getopts "I:" o; do case "${o}" in
+    I) donthide="yep" ;;
 #     a) artist="${OPTARG}" ;;
 #     t) title="${OPTARG}" ;;
 #     A) album="${OPTARG}" ;;
@@ -23,9 +25,10 @@
 #     d) date="${OPTARG}" ;;
 #     g) genre="${OPTARG}" ;;
 #     c) comment="${OPTARG}" ;;
-#     *) printf "Invalid option: -%s\\n" "$OPTARG" && err ;;
-# esac done
+    *) printf "Invalid option: -%s\\n" "$OPTARG" && err ;;
+esac done
 
+shift $((OPTIND - 1))
 file="$1"
 
 temp="$(mktemp)"
@@ -34,17 +37,25 @@ trap 'rm -f $temp' HUP INT QUIT TERM EXIT
 [ ! -f "$file" ] && echo 'Provide file to tag.' && exit 1
 
 vorbiscomment -l "$file" -c "$temp"
+
+if [ ! -n "$donthide" ]; then
+    image="$(grep "METADATA_BLOCK_PICTURE" $temp)"
+    sed -i -e '/METADATA_BLOCK_PICTURE/d' $temp
+fi
+
 grep "language=" $temp || echo "language=" >> $temp
 grep "artist=" $temp || echo "artist=" >> $temp
 grep "title=" $temp || echo "title=" >> $temp
 grep "album=" $temp || echo "album=" >> $temp
-grep "track=" $temp || echo "track=" >> $temp
-grep "total=" $temp || echo "total=" >> $temp
+# grep "track=" $temp || echo "track=" >> $temp
+# grep "total=" $temp || echo "total=" >> $temp
 grep "tags=" $temp || echo "tags=" >> $temp
-grep "genre=" $temp || echo "genre=" >> $temp
+# grep "genre=" $temp || echo "genre=" >> $temp
 grep "comment=" $temp || echo "comment=" >> $temp
 
 $EDITOR $temp
+
+[ -n "$image" ] && echo "$image" >> $temp
 vorbiscomment -w "$file" -c "$temp"
 
 # [ -z "$title" ] && echo 'Enter a title.' && read -r title
